CLASS zcl_lab_38_prod_price_hml DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    data price type i.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_38_PROD_PRICE_HML IMPLEMENTATION.
ENDCLASS.
