CLASS zcl_lab_46_mobile_operator_hml DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    class-events NEW_CALL EXPORTING value(EV_PHONE_NUMBER) type string.
    class-METHODS ASSIGN_CALL.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_46_MOBILE_OPERATOR_HML IMPLEMENTATION.


  METHOD assign_call.
    RAISE event NEW_CALL EXPORTING ev_phone_number = |+51-9999999|.
  ENDMETHOD.
ENDCLASS.
