CLASS zcl_lab_12_linux_hml DEFINITION INHERITING FROM ZCL_LAB_11_SYSTEM_HML
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_12_LINUX_HML IMPLEMENTATION.
ENDCLASS.
