CLASS zcl_lab_22_student_hml DEFINITION INHERITING FROM ZCL_LAB_21_CLASSROOM_HML
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS ASSIGN_STUDENT.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_22_STUDENT_HML IMPLEMENTATION.


  METHOD assign_student.
    data(lo_class) = new ZCL_LAB_21_CLASSROOM_HML(  ).
  ENDMETHOD.
ENDCLASS.
