CLASS zcl_lab_21_classroom_hml DEFINITION
  PUBLIC
  CREATE PROTECTED .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_21_CLASSROOM_HML IMPLEMENTATION.
ENDCLASS.
