CLASS zcl_lab_31_org_france_hml DEFINITION INHERITING FROM ZCL_LAB_29_ORGANIZATION_HML
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS: get_location REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_31_ORG_FRANCE_HML IMPLEMENTATION.


  METHOD get_location.
    rv_location = | Organización de Francia |.
  ENDMETHOD.
ENDCLASS.
