CLASS zcl_lab_23_company_hml DEFINITION
  PUBLIC
*  FINAL
  CREATE PUBLIC GLOBAL FRIENDS ZCL_LAB_24_PARTNER_HML.


  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
  data capital type string.
ENDCLASS.



CLASS ZCL_LAB_23_COMPANY_HML IMPLEMENTATION.
ENDCLASS.
