CLASS zcl_lab_28_logistics_hml DEFINITION INHERITING FROM zcl_lab_27_factory_hml
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS: PRODUCTION_LINE REDEFINITION,
             INPUT_PRODUCTS REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_28_LOGISTICS_HML IMPLEMENTATION.


    METHOD INPUT_PRODUCTS.
        rv_input = 'Input Products'.
    ENDMETHOD.


    METHOD PRODUCTION_LINE.
        rv_production = 'Production Line'.
    ENDMETHOD.
ENDCLASS.
