CLASS zcx_lab_57_format_unknown_hml DEFINITION INHERITING FROM cx_static_check
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCX_LAB_57_FORMAT_UNKNOWN_HML IMPLEMENTATION.
ENDCLASS.
