CLASS zcx_lab_56_no_date_hml DEFINITION INHERITING FROM cx_static_check
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCX_LAB_56_NO_DATE_HML IMPLEMENTATION.
ENDCLASS.
